name: EC2 demo
on: 
  push: 
    branches: 
      - main
jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
      - name: deploy to ec2 server
      run : |
        echo "${{secrets.EC2_SSH_KEY }}"
        chmod 600 demo-session-vpc.pem

        ssh -i demo-session-vpc.pem -o StrictHostKeyChecking=no ${{secrets.EC2_USERNAME}}@{{secrets.EC2_HOST}} << EOF

        cd demo 
        git pull origin main
        sudo cp -r * /var/www/html/
        sudo systemctl restart nginx

        EOF
