name: EC2 Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Website to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF

          cd ~/demo
          git pull origin main

          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/

          sudo systemctl restart nginx

          EOF
